import type { ConnectorSummary, Vehicle } from '@drivecentric-ai/shared';

export const connectorSeeds: ConnectorSummary[] = [
  ['dealership-website', 'Dealership Website', 'railway', 'live', true, ['read']],
  ['facebook-marketplace', 'Facebook Marketplace', 'local-agent', 'live', true, ['read', 'write', 'upload']],
  ['drivecentric', 'DriveCentric', 'extension', 'live', true, ['read', 'upload']],
  ['routeone-bank-brain', 'RouteOne / Bank Brain', 'railway', 'live', true, ['read', 'download', 'upload']],
  ['vauto', 'vAuto', 'local-agent', 'skeleton', false, ['read', 'download']],
  ['reconvision', 'ReconVision', 'local-agent', 'recording', false, ['read']],
  ['onemicro', '1Micro', 'local-agent', 'recording', false, ['read']],
  ['carfax', 'CARFAX', 'local-agent', 'skeleton', false, ['read', 'download']],
  ['window-sticker', 'Window Sticker', 'railway', 'skeleton', false, ['read', 'download']],
  ['accutrade', 'AccuTrade', 'local-agent', 'skeleton', false, ['read']],
  ['reynolds', 'Reynolds & Reynolds', 'local-agent', 'skeleton', false, ['read', 'download']],
  ['craigslist', 'Craigslist', 'local-agent', 'skeleton', false, ['read', 'write', 'upload']],
  ['offerup', 'OfferUp', 'local-agent', 'skeleton', false, ['read', 'write', 'upload']],
].map(([id, displayName, executionLocation, mode, enabled, capabilities]) => ({
  id: String(id),
  displayName: String(displayName),
  description: `${displayName} XConsole connector`,
  capabilities: capabilities as ConnectorSummary['capabilities'],
  executionLocation: executionLocation as ConnectorSummary['executionLocation'],
  mode: mode as ConnectorSummary['mode'],
  approvalRequiredForWrites: true,
  enabled: Boolean(enabled),
  authenticationStatus: enabled ? 'authenticated' : 'not-configured',
  lastSuccessfulSync: enabled ? '2026-07-23T12:00:00.000Z' : null,
  lastAttemptedSync: enabled ? '2026-07-23T12:00:00.000Z' : null,
  lastDurationMs: enabled ? 250 : null,
  recordsUpdated: enabled ? 1 : 0,
  currentError: null,
  reauthenticationRequired: false,
  logsUrl: `/api/connectors/${id}/runs`,
  failureScreenshotUrl: null,
}));

export const vehicleSeeds: Vehicle[] = [
  {
    id: 'synthetic-vehicle-1',
    vin: '1HGCM82633A004352',
    stockNumber: 'SYN-1001',
    year: 2024,
    make: 'Honda',
    model: 'Accord',
    trim: 'EX',
    mileage: 12000,
    retailPrice: 28995,
    cost: null,
    daysInStock: 18,
    websiteUrl: 'https://example.invalid/inventory/SYN-1001',
    photos: [],
    sourceStatuses: [
      {
        connectorId: 'dealership-website',
        displayName: 'Dealership Website',
        status: 'active',
        synchronizedAt: '2026-07-23T12:00:00.000Z',
        error: null,
        reauthenticationRequired: false,
        details: { fixture: true },
      },
      {
        connectorId: 'facebook-marketplace',
        displayName: 'Facebook Marketplace',
        status: 'draft',
        synchronizedAt: '2026-07-23T12:00:00.000Z',
        error: null,
        reauthenticationRequired: false,
        details: { liveTested: false },
      },
    ],
    salesTalkingPoints: ['Synthetic fixture vehicle', 'Verify live price and availability before quoting'],
    lastSynchronizedAt: '2026-07-23T12:00:00.000Z',
  },
];
