FROM node:22-alpine

ARG PNPM_FILTER
ENV PNPM_FILTER=${PNPM_FILTER}
WORKDIR /app

RUN corepack enable
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter "${PNPM_FILTER}..." build

CMD ["sh", "-c", "pnpm --filter \"$PNPM_FILTER\" start"]
